project:
  type: website
  output-dir: docs

website:
  title: "Jessica K. Higgins Ph.D."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      dark: solar
      light: pulse
    css: styles.css
    toc: true

editor: visual

